# Generated by Django 2.2.7 on 2019-11-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dld', '0001_initial'),
    ]

    operations = [
    ]
